"""Config package"""
from .settings import (
	settings,
	NEWS_TYPES,
	NEWS_SOURCES,
	KOCAELI_DISTRICTS,
	REQUIRED_NEWS_TYPES,
	NEWS_TYPE_PRIORITY,
	KOCAELISPOR_STADIUM,
	DEFAULT_STADIUM_RADIUS_KM,
	DEFAULT_SCRAPE_DAYS,
	IZMIT_FALLBACK_CENTER,
)

__all__ = [
	"settings",
	"NEWS_TYPES",
	"NEWS_SOURCES",
	"KOCAELI_DISTRICTS",
	"REQUIRED_NEWS_TYPES",
	"NEWS_TYPE_PRIORITY",
	"KOCAELISPOR_STADIUM",
	"DEFAULT_STADIUM_RADIUS_KM",
	"DEFAULT_SCRAPE_DAYS",
	"IZMIT_FALLBACK_CENTER",
]
